### PR TITLE
Fix tags search

### LINKED ISSUE #780: Fix on-click handler for tags
All tags currently redirect to discover page. It is needed to make this handler more specific:
- In a tribe: a click on a part-up tag (expanding from part-up tile) should trigger a search on this tribe with this tag as search argument (see original explanation by Erik below).
- On the tribe homepage: a click on the tribe tag should trigger a search on this tribe with this tag as search argument 
- On an activity detail: a click on the lane tag on an activity detail should link to activity board view (NB: tag on activity detail is also broken at this moment, but will be fixed shortly by Noel)

Within the tribe Customer Cocreation of Part-up there are already 34 part-ups. I wanted to make an overview on which ones of them have to do with implementation, and therefore all tagged them 'Implementatie'. When clicking the label 'Implementatie' on the part-up tile, I'm redirected to the discover page. Clicking the label there, doesn't work either. I would expect to get an overview of all part-ups within the tribe with the same label.

### PR DESCRIPTION
**Pull request by andreleon**
This PR fixes #780

### CODE REVIEW

File: app/packages/partup-client-base/client/discover.js [hunk 1]
```diff
@@ -111,6 +111,7 @@ Partup.client.discover = {
      * Helper to set prefill value
      */
     setPrefill: function(key, value) {
+        console.log(key, value)
```
Comment (noelheesen) [inline app/packages/partup-client-base/client/discover.js]: Forgot to remove console.log

File: app/packages/partup-client-base/components/Tag.js [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+                Router.go('discover-partups');
+                break;
+            case 'discover-tribes':
+                Partup.client.discover.setTribePrefill('textSearch', data.query);
+                Router.go('discover');
+                break;
+            case 'tribe-search':
+                Router.go(`/tribes/${data.slug}/partups?tag=${data.query}`);
+                break;
+            // case 'activity':
```
Comment (noelheesen) [inline app/packages/partup-client-base/components/Tag.js]: Do we need this in the future?

File: app/packages/partup-client-dropdowns/expander/toggler.js [hunk 3]
```diff
@@ -1,7 +1,9 @@
 Template.PartupToggler.onCreated(function() {
     var template = this;
 
-    template.expanded = new ReactiveVar(false);
+    const { reactiveExpander } = this.data;
+
+    template.expanded = reactiveExpander ? reactiveExpander : new ReactiveVar(false);
```
Comment (noelheesen) [inline app/packages/partup-client-dropdowns/expander/toggler.js]: || syntax prefered: `reactiveExpander || new ReactiveVar(false);`
